name: Local Deploy on Push

on:
  push:
    branches:
      - main   # or your default branch
  workflow_dispatch:  # manual trigger support

jobs:
  local-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest code (confirmation)
        run: echo "Code checked out on local machine"

      - name: Copy files to local Python server directory
        shell: powershell
        run: |
          $source = "$env:GITHUB_WORKSPACE"
          $destination = "C:\Users\yogra\Desktop\projects\simplewebpage"

          
          Remove-Item -Path "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue

          
          Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
